### ISSUE TITLE
Automatic pre-amp compensation

### ISSUE THREAD

**Issue by bhack** [lsp-plugins/lsp-plugins-para-equalizer#2] opened 2023-03-09 10:55 UTC
Can we add an automatic pre-amp [calc to avoid clipping](https://www.reddit.com/r/oratory1990/comments/optidf/comment/h68czk5/?utm_source=reddit&utm_medium=web2x&context=3)?

See also https://github.com/wwmm/easyeffects/issues/1592#issuecomment-1174973343

**Comment by sadko4u** [comment] 2023-03-10 13:43
It seems to be duplicate of this feature request:
https://github.com/sadko4u/lsp-plugins/issues/188

**Closed as completed** 2023-03-10 13:43 UTC
Labels: duplicate
